COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    ':sdnwise',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

remote_jar (
  name = 'sdnwise',
  out = 'sdn-wise-core-4.0.1-SNAPSHOT.jar',
  url = 'mvn:com.github.sdnwiselab:sdn-wise-core:4.0.1-SNAPSHOT',
  maven_coords = 'com.github.sdnwiselab:sdn-wise-core:4.0.1-SNAPSHOT',
  visibility = [ 'PUBLIC' ],
)
