COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:openflowj',
    '//lib:sdnwise',
    '//protocols/sdnwise/api:onos-protocols-sdnwise-api',
    '//protocols/sdnwise/protocol:onos-protocols-sdnwise-protocol',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
