COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:sdnwise',
    '//protocols/sdnwise/protocol:onos-protocols-sdnwise-protocol',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)
